# Generated by Django 5.0.6 on 2025-04-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to='session.sessionmember'),
        ),
    ]
